# Configuration for ManiaJS and Plugins.
# DO NOT CHANGE WHEN THE CONTROLLER IS RUNNING! CLOSE CONTROLLER AND REFRESH THE FILE!

config:
  debug: true

  # ManiaPlanet Dedicated Server
  server:
    game: 'trackmania' # Could be 'trackmania' or 'shootmania'
    address: '127.0.0.1'
    port: 5000
    authentication:
      username: 'SuperAdmin'
      password: 'SuperAdmin'

  # The users (logins) bellow will have masteradmin rights on start, when having those rights you could give others rights with the commands.
  masteradmins:
  - login

  # Database Settings
  db:
    dialect: 'mysql' # Can be mysql, mariadb, sqlite, mssql, postgres.
    # ! ==> SQLite3 Requires compilation, this means that you have to get build-essentials on linux, Visual Studio on Windows or XCode on Mac OS X.
    # When not having build tools, you will get warnings when starting for the first time or run the installation script.
    # You can ignore this, but can't use the dialects then!
    # To recompile run 'npm install sqlite3' in root

    # Global Non-driver-dependent settings:
    debug: false
    database: 'maniajs'
    authentication:
      username: 'root'
      password: ''
    pool:
      max: 5
      min: 0
      idle: 10000

    # Driver settings
    mysql:
      host: '127.0.0.1'
      port: 3306

    mariadb:
      host: '127.0.0.1'
      port: 3307

    mssql:
      host: '127.0.0.1'
      port: 1433

    postgres:
      host: '127.0.0.1'
      port: 5432

    sqlite:
      storage: './database.sqlite' # Path, relative to root of ManiaJS.

# Plugin Configuration
plugins:
  '@maniajs/plugin-help':

  '@maniajs/plugin-localrecords':
    recordlimit: 100
    displaylimit: 50

  '@maniajs/plugin-welcome':

#  '@maniajs/plugin-dedimania':
#    login: ****
#    dedimaniacode: ****
#    displaylimit: 50
