# CONFIGURATION FILE FOR MANIAJS

config:
  debug: true

  server:
    address: '127.0.0.1'
    port: 5000
    authentication:
      username: 'SuperAdmin'
      password: 'SuperAdmin'
  db:
    dialect: 'mysql' # Can be mysql, mariadb or sqlite.

    # ! ==> SQLite3 Requires compilation, this means that you have to get build-essentials on linux, Visual Studio on Windows or XCode on Mac OS X.
    # When not having build tools, you will get warnings when starting for the first time or run the installation script.
    # You can ignore this, but can't use the dialects then!
    # To recompile run 'npm install sqlite3' in root



    # Global Non-driver-dependent settings:
    database: 'maniajs'
    authentication:
      username: 'root'
      password: ''
    pool:
      max: 5
      min: 0
      idle: 10000

    # Driver settings
    mysql:
      host: '127.0.0.1'
      port: 3306

    mariadb:
      host: '127.0.0.1'
      port: 3307

    sqlite:
      storage: './database.sqlite' # Path, relative to root of Controller.JS

plugins:
  maniajs-plugin-sample:
    test: true
